### ISSUE TITLE
Timestamped transcripts not displaying when audio plays #71

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/oral-history#15]
Timestamped transcripts should display when user plays audio. The Shumyo Kojima interview complies with expected behavior: https://oralhistory.library.ucla.edu/catalog/21198-zz002kfkfw

The Megan McGresley interview should display a timestamped transcript when audio plays but does not: https://oralhistory.library.ucla.edu/catalog/21198-zz002knrcz

Here are Kristian's notes on the issue:

Acceptance criteria:

XML transcripts added to new items is not rendering properly, when compared to those 'pre-new-oh upload process'
Example: Properly rendering xml - https://oralhistory.library.ucla.edu/catalog/21198-zz002kd7t9?counter=5&q=black+business
Non rendering xml - https://oralhistory.library.ucla.edu/catalog/21198-zz002kpjm4
Expected behavior: When you click the play button next to a session section, a box of xml containing the transcript should be rendered

Actual behavior: The xml transcript is not being rendered

Steps taken:

Verified xml is in the proper place and linked to in DLCS OAI properly outputting xml file in correct field
Additional steps needed:

Verify any differences in content_files records Identify javascript error when play button clicked

GET blob:https://oralhistory.library.ucla.edu/8c6c73a5-57a4-44c5-a22d-df6760328a7f net::ERR_FILE_NOT_FOUND

After a dive into the code and logs, I believe this is an issue in the ruby application regarding the indexing job and have opened a ticket with scientist/notch8

https://gitlab.com/notch8/oral_history/-/issues/165

**Comment by aprilrieger** [comment]
They need to fix their feed, context: https://assaydepot.slack.com/archives/C03UFN7017A/p1679521344593419?thread_ts=1678998189.817939&cid=C03UFN7017A

**Comment by aprilrieger** [comment]
The field that we are indexing to display the transcripts is mods:location/mods:url[@usage="timed log" which doesn't exist on the [Megan LeGresley](https://webservices.library.ucla.edu/dldataprovider/oai2_0.do?metadataPrefix=mods&verb=GetR[%E2%80%A6]ntifier=oai:library.ucla.edu:digital2/21198-zz002knrcz) record

```
<mods:location>
  <mods:url usage="timed log">https://static.library.ucla.edu/oralhistory/xml/21198-zz002kfkjf-3-master.xml
  </mods:url>
</mods:location>
```

It would look like this in the feed
