### ISSUE TITLE
Install Google Tag Manager on oralhistory.library.ucla.edu #72

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/oral-history#16]
ISSUE

Universal Analytics (GA3) will no longer process new data in standard properties beginning July 1, 2023. The Library must set up and switch over to a Google Analytics 4 property and configure GTM to work with this new GA4 property.

ACTION NEEDED by May 2023

Install Google Tag Manager on oralhistory.liibrary.ucla.edu
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:
```
// <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T2SXV2');</script>
<!-- End Google Tag Manager --> 
```

**Comment by aprilrieger** [comment]
Pass Staging QA: I see the google tag in the header where it previously was not.

**Comment by tttkay** [comment]
Sharon Shafer confirms that GTM is gathering data.
