### ISSUE TITLE
Blacklight Upgrade

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#19]
# Testing QA Instructions:
https://github.com/scientist-softserv/oral-history/issues/19#issuecomment-1477281496

Testing on staging: 
Staging is: https://oralhistory-test.library.ucla.edu/
UN: & PW for auth are `oralhistory`
Admin user login (if needed): https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=mcualmilgnczhcga4gkqc4675a&h=scientist.1password.com

Please pay careful attention to the over written partials that are noted in the comment linked above.

# Summary

Newest Version of Blacklight is 7.33.1.  Blacklight should currently be running 7.10.  Running bootstrap 4.6.0.  

# Related
The app will require a rails upgrade in order to upgrade to the latest blacklight version.
Rails Upgrade Ticket: https://github.com/scientist-softserv/oral-history/issues/18

# Acceptance Criteria

- [x] -Bootstrap is running in the 7.33.1 

# Notes
Hopefully still at this link: https://github.com/projectblacklight/blacklight/releases?page=6
[Version 7.0.0](https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0)
New features
Bootstrap 4
Rails 5.2 support
[Webpacker support](https://github.com/projectblacklight/blacklight/wiki/Using-Webpacker-to-compile-javascript-assets)
JSON-API support
Solr 7.2 support
Dynamic solr schema by default
Additive configuration https://github.com/projectblacklight/blacklight/pull/1767
Defined properties in the SolrDocument class https://github.com/projectblacklight/blacklight/pull/1659
If you previously had a number of methods in your SolrDocument class like this:
def title
  self['title_ssim'].first
end
You can now simplify these by replacing with:

  include Blacklight::Solr::Document
  attribute :title, Blacklight::Types::String, 'title_tesim'
Bug fixes
if the application name isn't defined in the current language, fallback to the application_name in the default language. https://github.com/projectblacklight/blacklight/pull/1724
Upgrading
Add include Blacklight::DefaultComponentConfiguration to your catalog controller or

  configure_blacklight do |config|
    config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')
  end
Documents are now returned using JSON-API at /catalog/:id.json This only returns fields that are configured using add_show_field. If you want to receive the full Solr document (all fields) in the format they were in in Blacklight 6, you must add the configuration: config.raw_endpoint.enabled = true and the endpoint will be changed to /catalog/:id/raw.json

If you are using Blacklight::Solr::Response directly, note that the options to the initializer have changed. Where previously it took :solr_document_model it now takes a :blacklight_config option.

Partial changes
shared/ajax_modal has moved toshared/modal

Bootstrap 3 to 4 migration guide
For updating your Blacklight application from Bootstrap 3 to 4, please review and contribute to the [migration guide](https://github.com/projectblacklight/blacklight/wiki/Bootstrap-3-to-4-Migration-Guide).

**Comment by summer-cook** [comment]
Currently blocked by rails upgrade ticket: 



![Image](https://user-images.githubusercontent.com/73361970/225054402-c2bc6bb1-f457-4c8f-8cf4-a3fb0c1d5eed.png)


blacklight 7.33.1 depends on Rails 7

**Comment by aprilrieger** [comment]
Making new tickets for updating the overrides

**Comment by aprilrieger** [comment]
Checkout my branch:
branch: i18-rails-upgrade-6point1
get `.env.development` here: https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=ok6rwracafccnhrhur7usyfwoi&h=scientist.1password.com

gem install stack_car -v0.16.0
gem install dory

dory up
sc build
sc up

navigate to `http://oralhistory.test/users/sign_in`
login: creds in the .env

navigate to `http://oralhistory.test/admin`

run importer OR run in web container `rake db:migrate import[10]` [#] <— amount of works you import

Need troubleshooting tips?
If you do a `dc down -v`, odds are you will want to do a `rm -rf tmp/*`

**Comment by aprilrieger** [comment]
rails upgrade notes:
updated to 5.2 latest
updated to 6.0
updated to 6.1

**Comment by aprilrieger** [comment]
Checkout main branch
get `.env.development` here: https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=ok6rwracafccnhrhur7usyfwoi&h=scientist.1password.com

```
gem install stack_car -v0.16.0
gem install dory

dory up
sc build
sc up
```

navigate to http://oralhistory.test/users/sign_in && login: creds in the .env

navigate to http://oralhistory.test/admin

run importer OR run in web container `rake db:migrate import[10]` [#] <— amount of works you import

Need troubleshooting tips?
If you do a `dc down -v`, odds are you will want to do a `rm -rf tmp/*`

List of views that have been upgraded from Blacklight v7.10 - 7.33.1 that our application currently has in the applications local files.

https://github.com/projectblacklight/blacklight/compare/v7.10.0...v7.33.1

- [ ] app/views/catalog/_constraints.html.erb
- [ ] app/views/catalog/_email_form.html.erb
- [ ] app/views/catalog/_facet_layout.html.erb
- [ ] app/views/catalog/_facets.html.erb
- [ ] app/views/catalog/_home_text.html.erb
- [ ] app/views/catalog/_index.html.erb
- [ ] app/views/catalog/_search_form.html.erb
- [ ] app/views/catalog/_search_results.html.erb
- [ ] app/views/catalog/_show_tools.html.erb
- [ ] app/views/catalog/_start_over.html.erb
- [ ] app/views/catalog/show.html.erb
- [ ] app/views/search_history/index.html.erb
- [ ] app/views/shared/_header_navbar.html.erb
- [ ] app/models/search_builder.rb
- [ ] app/controllers/concerns/blacklight/bookmarks.rb
- [x] app/services/blacklight/field_retriever.rb
- [ ] All full_text blacklight partials
- [ ] All interviewee blacklight partials

Steps:
- [ ] Compare the partial against what was changed form 7.10 to 7.33.1 and update the overriden file as necessary: https://github.com/projectblacklight/blacklight/compare/v7.10.0...v7.33.1
- [ ] Test the changes in your browser for the views functionality is still working
- [ ] If you had to update the file and there is not a pre-existing OVERRIDE notes, please add one with why the partial was overriden, if you can tell.
Example: `<%# OVERRIDE: Blacklight v7.33.1 to provide theming for the clients needs %>`

**Comment by DiemBTran** [comment]
This passes SoftServ QA. Mobbed with April and Kirk to check each of the partials that was updated in [this comment](https://github.com/scientist-softserv/oral-history/issues/19#issuecomment-1477281496).

**Comment by aprilrieger** [comment]
![Image](https://user-images.githubusercontent.com/63515648/230661057-db54b832-c8ec-47ae-9bc2-dededd161bc5.png)
