### ISSUE TITLE
Run Bundler Audit After Rails Upgrade

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#20]
# Summary

After Rails upgrade run Bundler Audit to see if any gems need to be updated.  

# Related
Cannot work on this until rails upgrade is complete
Rails Upgrade Ticket: https://github.com/scientist-softserv/oral-history/issues/18

# Acceptance Criteria

- [x] List of gems that needed to be updated. 

# Notes
Brakeman and Bundler Audit before the upgrades: https://docs.google.com/document/d/1tXW9Jvbk1wx7fE_fOmvvfXfaVL4awpwbfrsvuwgmmKA/edit

**Comment by aprilrieger** [comment]
![Image](https://user-images.githubusercontent.com/63515648/230661218-73269e45-91fb-4cae-8b37-5888b63872cd.png)
