### ISSUE TITLE
Docker updates to get app running on M1s

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#21]
# Summary

The docker image being used does not support M1 chips for macs.  In order for the project to easily be worked on the app needs to load for both M1 and intel chips for mac.  

# Acceptance criteria

- [ ] Make necessary changes for the app to work on M1 macs.

**Comment by labradford** [comment]
https://playbook-staging.notch8.com/en/dev/docker/troubleshooting/running-docker-on-apple-silicon

**Comment by labradford** [comment]
# Commented out for development purposes with Apple M1 Silicon Procesing Chips
  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker

**Comment by aprilrieger** [comment]
`rake app:update:bin`

**Comment by jhriv** [comment]
I verified that `touch .env.development; docker compose build; docker compose up` brings up the Oral History container locally on an M2 Mac
