### ISSUE TITLE
Upgrade Solr 7.7 to 8.11

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/oral-history#25]
## Testing
Need to kick off a new importer & test application for imported works. Do you see the new works? Do you have access to their images?

Staging: https://oralhistory-test.library.ucla.edu
authentication un & pw: oralhistory

Signing: https://oralhistory-test.library.ucla.edu/users/sign_in
Kick off importer: https://oralhistory-test.library.ucla.edu/admin
sigin credentials: https://start.1password.com/open/i?a=LTLZ652TT5H5FHMYMASSH7PIXM&v=huuakin4bu4xanlhktv42qheam&i=mcualmilgnczhcga4gkqc4675a&h=scientist.1password.com

click "run importer"

# story
upgrade solr from v. 7.7 to 8.11

# Related
See spike for more notes & resources on how to accomplish this ticket: https://github.com/scientist-softserv/oral-history/issues/22

# implementation suggestions
- [x] The steps listed on this comment may be helpful to consider: https://github.com/scientist-softserv/oral-history/issues/22#issuecomment-1468585139
- [x] This one is important: after app is upgraded, reindex all items. 

# acceptance criteria
- [x] app is running solr 8.11

**Comment by summer-cook** [comment]
currently blocked by rails upgrade & blacklight upgrade

**Comment by aprilrieger** [comment]
Kicked off importer after deployment.

**Comment by aprilrieger** [comment]
From John in slack: https://assaydepot.slack.com/archives/C03UFN7017A/p1680644064461869?thread_ts=1680209296.596859&cid=C03UFN7017A



![Image](https://user-images.githubusercontent.com/63515648/230661001-3ac44b02-32d3-4bcd-8a33-c94ee243ae2b.png)
