### ISSUE TITLE
Due End of October: Support for Video Files

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#36]
# Summary

SoftServ will complete and remediate work for in-app playback of video files and related user interface
features. An example of such a work (which provides a case for testing acceptance) is:

-  https://oralhistory.library.ucla.edu/catalog/21198-zz002jxz7z?counter=1&q=alan+kay

Currently, video playback is not functioning and clicking the video play button in the UI simply
activates audio playback.

# Acceptance Criteria
- [ ] Items with a video will play in a video player
- [ ] Video player has skip 10 seconds feature
- [ ] Old video player code is removed from app

# Notes
Item with a video: https://oralhistory.library.ucla.edu/catalog/21198-zz002jxz7z?counter=1&q=alan+kay

**Comment by labradford** [comment]
more info on issue https://github.com/scientist-softserv/oral-history/issues/2

**Comment by labradford** [comment]
- Current video support is not working.
- Client wants to have better controls (ie 10 sec forward/back)
We recommended removing current player and adding videojs.com

**Comment by aprilrieger** [comment]
This has been deployed to staging, passed UAT. Deployed to production and we are witnessing no video in the video player. Needing to troubleshoot this in production on their infrastructure.

**Comment by aprilrieger** [comment]
This is currently love and working on the site.
