### ISSUE TITLE
Convert app deployment to Rancher managed Kubernetes

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#40]
# Summary

Looking forward, UCLA Library will be decommissioning our Docker Swarm environment and migrating all existing hosted applications to a Rancher managed Kubernetes cluster. We'll be Argo CD with helm charts to manage the deployments.
Is the creation and maintenance of the helm charts within Scientist's scope of work, or is this something that UCLA Library will handle?

# Acceptance Criteria

- [ ] Point ticket and provide estimate for moving to helm charts
- [ ] send estimate to T-Kay to see if this is work we should take on
- if approved this acceptance criteria becomes work to add the helm charts.

**Comment by aprilrieger** [comment]
@crisr15 How did we want to handle the workflow of this ticket? Is this considered closed? This also in not urgent, thank you.
