### ISSUE TITLE
New contract internal kick-off

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/oral-history#57]
## Summary
Client Kick-off meeting is Thursday 
Internal Kick-off is Wednesday

[SOW](https://drive.google.com/file/d/1dLa47R6bGxnToqidDwuY8bpomQ0huFGQ/view?usp=drive_link)

This ticket is in prep for the new maintenance contract that kicks off this month with UCLA OH. This contract cover 8 hours of development time plus an additional 4 hours of pairing. Our kick off meeting is August 15, which is where we will discuss what they want us to allocate the 8 hours to this month. Possible scope for the development work throughout the year includes:

- Component upgrades
- Backlog chores (update test coverage, ensure lint is passing, budler audit, brakeman audit)
- Push-Button Updates
- Session XMLs not showing
- UI Updates ( Search Result, Header UI improvement, Item Page)
- Bugs (audio icon)
- Consulting

## Acceptance Criteria
- [x] SOW has been reviewed
- [x] Questions/discussion topics for client kick-off meeting are added to this ticket

**Comment by bkiahstroud** [comment]
Discussion topics have been added to [the meeting note](https://docs.google.com/document/d/1fg6DuZQA3kdXSHeMLB0tYAG7i3bId_AgUwkRCIgehJE/edit)
